- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC Variables
      include_vars:
        file: /home/ubuntu/ansible-aws-vpc/vars/vpc_setup.yml

    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpcCidr }}"
        region: "{{ region }}"
        dns_support: true
        dns_hostnames: true
        tenancy: default
        state: "{{ state }}"
      register: vpcout

    - name: Debug VPC Information
      debug:
        msg: "VPC created with ID: {{ vpcout.vpc.id }}"

